[package]
name = "justkeydding-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
midly = "0.5"
indicatif = "0.17.1"
glob = "0.3.0"
serde = { version = "1.0.147", features = ["derive"]}
serde_json = "1.0.87"
clap = { version ="4.0.18", features = ["derive"]}